import {createClient} from './db/client.js';

const api=createClient(), $=s=>document.querySelector(s);
let seriesId=null, role=null, isHost=false, pc=null, channel=null, connected=false, localRematch=false, peerRematch=false;
const status=$('#status'), start=$('#start'), pairing=$('#pairing'), game=$('#game'), link=$('#link'), board=$('#board');
const encode=value=>btoa(unescape(encodeURIComponent(JSON.stringify(value)))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const decode=value=>JSON.parse(decodeURIComponent(escape(atob(value.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-value.length%4)%4)))));
const urlFor=value=>`${location.origin}${location.pathname}#${encode(value)}`;
function setStatus(text,error=false){status.textContent=text;status.className=error?'error':'';}
function waitGathering(peer){return new Promise(resolve=>{if(peer.iceGatheringState==='complete')return resolve();const timeout=setTimeout(resolve,3000);peer.addEventListener('icegatheringstatechange',()=>{if(peer.iceGatheringState==='complete'){clearTimeout(timeout);resolve();}},{once:true});});}
function wireChannel(c){channel=c;c.onopen=()=>{connected=true;setStatus('Connected.');render();};c.onclose=()=>{connected=false;setStatus('Opponent disconnected.',true);render();};c.onmessage=async event=>{try{const message=JSON.parse(event.data);if(message.type==='move'){await api.call('move.record',{seriesId,role:message.role,square:message.square});render();}if(message.type==='rematch-accept'){peerRematch=true;render();maybeStartRematch();}if(message.type==='rematch-start'){await api.call('rematch.create',{seriesId});localRematch=peerRematch=false;render();}}catch(error){setStatus(error.message,true);}};}
function send(message){if(channel?.readyState==='open')channel.send(JSON.stringify(message));}
async function createOffer(hostRole){isHost=true;role=hostRole;seriesId=crypto.randomUUID();await api.call('series.create',{seriesId,role});pc=new RTCPeerConnection();wireChannel(pc.createDataChannel('game'));const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitGathering(pc);showPairing('Invitation created','Send this invitation link to your friend. Waiting for their reply.',urlFor({type:'invite',seriesId,hostRole,offer:pc.localDescription}));}
async function acceptInvite(data){isHost=false;seriesId=data.seriesId;role=data.hostRole==='X'?'O':'X';await api.call('series.join',{seriesId,hostRole:data.hostRole});pc=new RTCPeerConnection();pc.ondatachannel=event=>wireChannel(event.channel);await pc.setRemoteDescription(data.offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await waitGathering(pc);showPairing('Reply link created','Send this reply link back to the host. They must open it next.',urlFor({type:'reply',seriesId,offer:data.offer,answer:pc.localDescription}));render();}
async function acceptReply(data){seriesId=data.seriesId;const s=await api.call('series.state',{seriesId});if(!data.offer)throw Error('This reply is unusable.');isHost=true;role=s.role;pc=new RTCPeerConnection();wireChannel(pc.createDataChannel('game'));await pc.setLocalDescription(data.offer);await pc.setRemoteDescription(data.answer);setStatus('Connecting…');pairing.hidden=true;game.hidden=false;render();}
function showPairing(title,text,value){$('#pairing-title').textContent=title;$('#pairing-text').textContent=text;link.value=value;pairing.hidden=false;start.hidden=true;}
function winnerText(outcome){return outcome==='draw'?'Draw.':`${outcome} wins.`;}
async function render(){if(!seriesId)return refreshHistory();const s=await api.call('series.state',{seriesId});start.hidden=true;game.hidden=false;$('#roles').textContent=`You are ${role}. ${s.match.status==='active'?`${s.turn}'s turn.`:winnerText(s.match.outcome)}`;board.className='board';board.replaceChildren(...Array.from({length:9},(_,square)=>{const move=s.moves.find(m=>m.square===square);const b=document.createElement('button');b.className='square';b.textContent=move?.role||'';b.disabled=!!move||s.match.status!=='active'||s.turn!==role||!connected;b.onclick=()=>play(square);return b;}));const rem=$('#rematch');rem.hidden=s.match.status!=='completed';if(!rem.hidden){$('#rematch-button').disabled=localRematch||!connected;$('#rematch-button').textContent=localRematch?'Rematch accepted':'Rematch?';$('#rematch-status').textContent=localRematch&&peerRematch?' Starting…':localRematch?' Waiting for opponent…':'';}await refreshHistory();}
async function play(square){try{const s=await api.call('move.record',{seriesId,role,square});send({type:'move',role,square});render();}catch(error){setStatus(error.message,true);}}
function maybeStartRematch(){if(localRematch&&peerRematch&&isHost){api.call('rematch.create',{seriesId}).then(()=>{send({type:'rematch-start'});localRematch=peerRematch=false;render();}).catch(e=>setStatus(e.message,true));}}
async function refreshHistory(){const history=await api.call('history.list');const h=$('#history');h.replaceChildren(...(history.length?history.map(item=>{const b=document.createElement('button');b.textContent=`Match ${item.number}: ${winnerText(item.outcome)}`;b.onclick=()=>replay(item.match_id);return b;}):[Object.assign(document.createElement('p'),{textContent:'No completed matches yet.',className:'muted'})]));}
async function replay(matchId){const {match,moves}=await api.call('match.get',{matchId});const text=moves.map(m=>`${m.ordinal}. ${m.role} → ${m.square+1}`).join(', ');alert(`Match ${match.number}: ${winnerText(match.outcome)}\n${text}`);}
$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(link.value);setStatus('Link copied.');}catch{link.select();document.execCommand('copy');setStatus('Link selected; copy it to send.');}};
document.querySelectorAll('[data-role]').forEach(button=>button.onclick=()=>createOffer(button.dataset.role).catch(e=>setStatus(e.message,true)));
$('#rematch-button').onclick=()=>{localRematch=true;send({type:'rematch-accept'});render();maybeStartRematch();};
async function boot(){try{await api.call('workspace.init');const raw=location.hash.slice(1);if(raw){const data=decode(raw);history.replaceState(null,'',location.pathname);if(data.type==='invite')await acceptInvite(data);else if(data.type==='reply')await acceptReply(data);else throw Error('Unusable game link.');}else setStatus('Choose a piece to create an invitation.');await refreshHistory();}catch(error){setStatus(error.message||'Could not open this game link.',true);}}
boot();
