import {createClient} from './db/client.js';

const api=createClient(), $=s=>document.querySelector(s);
let seriesId=null, role=null, isHost=false, pc=null, channel=null, connected=false, localRematch=false, peerRematch=false, scannerStream=null, scannerFrame=null;
const status=$('#status'), start=$('#start'), pairing=$('#pairing'), game=$('#game'), link=$('#link'), board=$('#board');
const legacyEncode=value=>btoa(unescape(encodeURIComponent(JSON.stringify(value)))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const legacyDecode=value=>JSON.parse(decodeURIComponent(escape(atob(value.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-value.length%4)%4)))));
function bytesToText(bytes){let text='';for(let offset=0;offset<bytes.length;offset+=0x8000)text+=String.fromCharCode(...bytes.subarray(offset,offset+0x8000));return text;}
function textToBytes(text){const padded=text.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-text.length%4)%4);return Uint8Array.from(atob(padded),char=>char.charCodeAt(0));}
async function encode(value){if(!globalThis.CompressionStream)return `j${legacyEncode(value)}`;const bytes=new TextEncoder().encode(JSON.stringify(value));const stream=new Blob([bytes]).stream().pipeThrough(new CompressionStream('deflate-raw'));return `z${btoa(bytesToText(new Uint8Array(await new Response(stream).arrayBuffer()))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}`;}
async function decode(value){if(!value.startsWith('z'))return legacyDecode(value.startsWith('j')?value.slice(1):value);if(!globalThis.DecompressionStream)throw Error('This browser cannot open a compressed pairing link.');const stream=new Blob([textToBytes(value.slice(1))]).stream().pipeThrough(new DecompressionStream('deflate-raw'));return JSON.parse(await new Response(stream).text());}
const urlFor=async value=>`${location.origin}${location.pathname}#${await encode(value)}`;
async function payloadFromLink(value){const url=new URL(value.trim(),location.href);if(!url.hash)throw Error('Paste the reply link your friend sent.');return decode(url.hash.slice(1));}
function setStatus(text,error=false){status.textContent=text;status.className=error?'error':'';}
function stopScanner(){if(scannerFrame){cancelAnimationFrame(scannerFrame);scannerFrame=null;}if(scannerStream){scannerStream.getTracks().forEach(track=>track.stop());scannerStream=null;}const video=$('#scanner-video');video.pause();video.srcObject=null;$('#scanner').hidden=true;}
async function useScannedLink(value,expectedType){stopScanner();try{const data=await payloadFromLink(value);if(data.type!==expectedType)throw Error(expectedType==='invite'?'Scan your friend’s invitation QR code.':'Scan your friend’s reply QR code.');if(expectedType==='invite')await acceptInvite(data);else await acceptReply(data);}catch(error){setStatus(error.message||'That QR code could not be read as a game link.',true);}}
async function startScanner(expectedType){if(!globalThis.jsQR)throw Error('QR scanning is unavailable in this browser. Paste the link instead.');if(!navigator.mediaDevices?.getUserMedia)throw Error('This browser cannot access a camera. Paste the link instead.');stopScanner();const scanner=$('#scanner'),video=$('#scanner-video');$('#scanner-title').textContent=expectedType==='invite'?'Scan invitation QR code':'Scan reply QR code';$('#scanner-text').textContent=expectedType==='invite'?'Point your camera at the host’s invitation QR code.':'Point your camera at your friend’s reply QR code.';scanner.hidden=false;try{scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=scannerStream;await video.play();const canvas=document.createElement('canvas'),context=canvas.getContext('2d',{willReadFrequently:true});const scan=()=>{if(!scannerStream)return;if(video.readyState>=video.HAVE_CURRENT_DATA){canvas.width=video.videoWidth;canvas.height=video.videoHeight;context.drawImage(video,0,0);const result=globalThis.jsQR(context.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height,{inversionAttempts:'dontInvert'});if(result){useScannedLink(result.data,expectedType);return;}}scannerFrame=requestAnimationFrame(scan);};scan();}catch(error){stopScanner();if(error.name==='NotAllowedError')throw Error('Camera permission was not granted. Paste the link instead.');if(error.name==='NotFoundError')throw Error('No camera is available. Paste the link instead.');throw Error('Could not start the camera. Paste the link instead.');}}
function waitGathering(peer){return new Promise(resolve=>{if(peer.iceGatheringState==='complete')return resolve();const timeout=setTimeout(resolve,3000);peer.addEventListener('icegatheringstatechange',()=>{if(peer.iceGatheringState==='complete'){clearTimeout(timeout);resolve();}},{once:true});});}
function wireChannel(c){channel=c;c.onopen=()=>{connected=true;pairing.hidden=true;setStatus('Connected.');render();};c.onclose=()=>{connected=false;setStatus('Opponent disconnected.',true);render();};c.onmessage=async event=>{try{const message=JSON.parse(event.data);if(message.type==='move'){await api.call('move.record',{seriesId,role:message.role,square:message.square});render();}if(message.type==='rematch-accept'){peerRematch=true;render();maybeStartRematch();}if(message.type==='rematch-start'){await api.call('rematch.create',{seriesId});localRematch=peerRematch=false;render();}}catch(error){setStatus(error.message,true);}};}
function send(message){if(channel?.readyState==='open')channel.send(JSON.stringify(message));}
async function createOffer(hostRole){isHost=true;role=hostRole;seriesId=crypto.randomUUID();await api.call('series.create',{seriesId,role});pc=new RTCPeerConnection();wireChannel(pc.createDataChannel('game'));const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitGathering(pc);showPairing('Invitation created','Send this invitation link to your friend. Keep this page open; when they reply, paste their reply link below.',await urlFor({type:'invite',seriesId,hostRole,offer:pc.localDescription}));$('#apply-reply').hidden=false;}
async function acceptInvite(data){isHost=false;seriesId=data.seriesId;role=data.hostRole==='X'?'O':'X';await api.call('series.join',{seriesId,hostRole:data.hostRole});pc=new RTCPeerConnection();pc.ondatachannel=event=>wireChannel(event.channel);await pc.setRemoteDescription(data.offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await waitGathering(pc);showPairing('Reply link created','Send this reply link back to the host. They keep the invitation page open and paste this reply there.',await urlFor({type:'reply',seriesId,answer:pc.localDescription}));render();}
async function acceptReply(data){if(!isHost||!pc||!seriesId||seriesId!==data.seriesId||pc.localDescription?.type!=='offer')throw Error('Return to the invitation page that is still open, then paste this reply link there.');if(!data.answer)throw Error('This reply is unusable.');await pc.setRemoteDescription(data.answer);setStatus('Connecting…');pairing.hidden=true;game.hidden=false;render();}
function showPairing(title,text,value){$('#pairing-title').textContent=title;$('#pairing-text').textContent=text;link.value=value;const qr=$('#qr');try{const code=globalThis.qrcode(0,'L');code.addData(value);code.make();qr.innerHTML=code.createSvgTag({cellSize:4,margin:0,scalable:true});}catch{qr.replaceChildren();}pairing.hidden=false;start.hidden=true;}
function winnerText(outcome){return outcome==='draw'?'Draw.':`${outcome} wins.`;}
async function render(){if(!seriesId)return refreshHistory();const s=await api.call('series.state',{seriesId});start.hidden=true;game.hidden=false;$('#roles').textContent=`You are ${role}. ${s.match.status==='active'?`${s.turn}'s turn.`:winnerText(s.match.outcome)}`;board.className='board';board.replaceChildren(...Array.from({length:9},(_,square)=>{const move=s.moves.find(m=>m.square===square);const b=document.createElement('button');b.className='square';b.textContent=move?.role||'';b.disabled=!!move||s.match.status!=='active'||s.turn!==role||!connected;b.onclick=()=>play(square);return b;}));const rem=$('#rematch');rem.hidden=s.match.status!=='completed';if(!rem.hidden){$('#rematch-button').disabled=localRematch||!connected;$('#rematch-button').textContent=localRematch?'Rematch accepted':'Rematch?';$('#rematch-status').textContent=localRematch&&peerRematch?' Starting…':localRematch?' Waiting for opponent…':'';}await refreshHistory();}
async function play(square){try{const s=await api.call('move.record',{seriesId,role,square});send({type:'move',role,square});render();}catch(error){setStatus(error.message,true);}}
function maybeStartRematch(){if(localRematch&&peerRematch&&isHost){api.call('rematch.create',{seriesId}).then(()=>{send({type:'rematch-start'});localRematch=peerRematch=false;render();}).catch(e=>setStatus(e.message,true));}}
async function refreshHistory(){const history=await api.call('history.list');const h=$('#history');h.replaceChildren(...(history.length?history.map(item=>{const b=document.createElement('button');b.textContent=`Match ${item.number}: ${winnerText(item.outcome)}`;b.onclick=()=>replay(item.match_id);return b;}):[Object.assign(document.createElement('p'),{textContent:'No completed matches yet.',className:'muted'})]));}
async function replay(matchId){const {match,moves}=await api.call('match.get',{matchId});const text=moves.map(m=>`${m.ordinal}. ${m.role} → ${m.square+1}`).join(', ');alert(`Match ${match.number}: ${winnerText(match.outcome)}\n${text}`);}
$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(link.value);setStatus('Link copied.');}catch{link.select();document.execCommand('copy');setStatus('Link selected; copy it to send.');}};
$('#apply-reply-button').onclick=()=>{payloadFromLink($('#reply-link').value).then(data=>{if(data.type!=='reply')throw Error('Paste a reply link.');return acceptReply(data);}).catch(error=>setStatus(error.message,true));};
$('#scan-invite-button').onclick=()=>startScanner('invite').catch(error=>setStatus(error.message,true));
$('#scan-reply-button').onclick=()=>startScanner('reply').catch(error=>setStatus(error.message,true));
$('#stop-scanner-button').onclick=stopScanner;
addEventListener('pagehide',stopScanner);
document.querySelectorAll('[data-role]').forEach(button=>button.onclick=()=>createOffer(button.dataset.role).catch(e=>setStatus(e.message,true)));
$('#rematch-button').onclick=()=>{localRematch=true;send({type:'rematch-accept'});render();maybeStartRematch();};
async function boot(){try{await api.call('workspace.init');const raw=location.hash.slice(1);if(raw){const data=await decode(raw);history.replaceState(null,'',location.pathname);if(data.type==='invite')await acceptInvite(data);else if(data.type==='reply'){showPairing('Reply link received','Return to the host invitation page that is still open and paste this link there.',await urlFor(data));}else throw Error('Unusable game link.');}else setStatus('Choose a piece to create an invitation.');await refreshHistory();}catch(error){setStatus(error.message||'Could not open this game link.',true);}}
boot();
