let SQL, db, storage, ready=false, queue=Promise.resolve();
const schema=`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS series(id TEXT PRIMARY KEY, role TEXT NOT NULL CHECK(role IN ('X','O')), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS matches(id INTEGER PRIMARY KEY, series_id TEXT NOT NULL REFERENCES series(id), number INTEGER NOT NULL, status TEXT NOT NULL, outcome TEXT, UNIQUE(series_id,number));
CREATE TABLE IF NOT EXISTS moves(id INTEGER PRIMARY KEY, match_id INTEGER NOT NULL REFERENCES matches(id), ordinal INTEGER NOT NULL, role TEXT NOT NULL CHECK(role IN ('X','O')), square INTEGER NOT NULL CHECK(square BETWEEN 0 AND 8), UNIQUE(match_id,ordinal), UNIQUE(match_id,square));`;
const rows=(sql,args=[])=>{const s=db.prepare(sql);try{s.bind(args);const out=[];while(s.step())out.push(s.getAsObject());return out;}finally{s.free();}};
async function init(){if(ready)return; importScripts(new URL('../../vendor/sql.js/sql-wasm.js',self.location.href)); SQL=await initSqlJs({locateFile:()=>new URL('../../vendor/sql.js/sql-wasm.wasm',self.location.href).href}); const {WorkspaceStorage}=await import('./persistence.js'); storage=new WorkspaceStorage();const bytes=await storage.open();db=new SQL.Database(bytes);db.run(schema);if(!bytes.length)await persist();ready=true;}
async function persist(){const bytes=db.export();try{await storage.save(bytes);}catch(error){db.close();db=new SQL.Database(await storage.load());db.run('PRAGMA foreign_keys=ON');throw error;}}
const id=()=>crypto.randomUUID(); const other=r=>r==='X'?'O':'X';
function state(seriesId){const series=rows('SELECT * FROM series WHERE id=?',[seriesId])[0];if(!series)throw Error('Unknown game series');const match=rows('SELECT * FROM matches WHERE series_id=? ORDER BY number DESC LIMIT 1',[seriesId])[0];const moves=match?rows('SELECT ordinal,role,square FROM moves WHERE match_id=? ORDER BY ordinal',[match.id]):[];return {...series,match,moves,turn:moves.length%2===0?(match.number%2?'X':'O'):other(moves.at(-1).role)};}
function outcome(moves){const b=Array(9);for(const m of moves)b[m.square]=m.role;for(const [a,c,d] of [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]])if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a];return moves.length===9?'draw':null;}
function createSeries({seriesId=id(),role}){if(!['X','O'].includes(role))throw Error('Choose X or O');db.run('INSERT INTO series VALUES(?,?,?)',[seriesId,role,new Date().toISOString()]);db.run('INSERT INTO matches(series_id,number,status) VALUES(?,?,?)',[seriesId,1,'active']);return state(seriesId);}
function joinSeries({seriesId,hostRole}){return createSeries({seriesId,role:other(hostRole)});}
function move({seriesId,role,square}){const s=state(seriesId);if(s.match.status!=='active'||s.turn!==role||!Number.isInteger(square)||s.moves.some(m=>m.square===square))throw Error('Invalid move');db.run('INSERT INTO moves(match_id,ordinal,role,square) VALUES(?,?,?,?)',[s.match.id,s.moves.length+1,role,square]);const moves=rows('SELECT ordinal,role,square FROM moves WHERE match_id=? ORDER BY ordinal',[s.match.id]);const result=outcome(moves);if(result)db.run("UPDATE matches SET status='completed',outcome=? WHERE id=?",[result,s.match.id]);return state(seriesId);}
function rematch({seriesId}){const s=state(seriesId);if(s.match.status!=='completed')throw Error('Match is not complete');db.run('INSERT INTO matches(series_id,number,status) VALUES(?,?,?)',[seriesId,s.match.number+1,'active']);return state(seriesId);}
function history(){return rows("SELECT s.id series_id,s.role,m.number,m.outcome,m.id match_id FROM series s JOIN matches m ON m.series_id=s.id WHERE m.status='completed' ORDER BY m.id DESC");}
async function dispatch(op,p){await init();let r;const write=['series.create','series.join','move.record','rematch.create'].includes(op);if(write)db.run('BEGIN');try{if(op==='workspace.init')r={ok:true};else if(op==='series.create')r=createSeries(p);else if(op==='series.join')r=joinSeries(p);else if(op==='series.state')r=state(p.seriesId);else if(op==='move.record')r=move(p);else if(op==='rematch.create')r=rematch(p);else if(op==='history.list')r=history();else if(op==='match.get'){const m=rows('SELECT * FROM matches WHERE id=?',[p.matchId])[0];r={match:m,moves:rows('SELECT ordinal,role,square FROM moves WHERE match_id=? ORDER BY ordinal',[p.matchId])};}else throw Error('Unknown operation');if(write){db.run('COMMIT');await persist();}return r;}catch(e){if(write)try{db.run('ROLLBACK')}catch{}throw e;}}
self.onmessage=({data})=>{queue=queue.then(async()=>{try{self.postMessage({id:data.id,result:await dispatch(data.op,data.payload||{})});}catch(error){self.postMessage({id:data.id,error:error.message});}})};
